
# Top level defaults
title: Talking To Ghosts
description: Ricky is a web developer, python hacker, and blogger in DC.
permalink: /:categories/:title
author:
  twitter: _rickyreal
url: https://rickydeal.io

sass:
  style: compressed # possible values: nested, expanded, compact, and compressed

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed

# XML/RSS Feed
feed:
  path: ghost.xml

# Collections
collections:
  portfolio:
    permalink: /:collection/:name
    output: true
    order:
      - esaan_tumbar.md
      - prt_monitor.md
      - wvu_mobile.md
      - image_recognition.md
      - portfolio.md
      - stroboscope.md
      - star_trek_computer.md

# Defaults for different page types
defaults:
  -
    scope:
      path: "assets/**/*.pdf"
    values:
      sitemap: false
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default
  -
    scope:
      path: ""
      type: "portfolio"
    values:
      layout: details
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      image: null
      youtube: null
      spotify: null
      soundcloud: null
      categories: []
      tags: []