
# Top level defaults
title: Conversations With A Ghost
description: Ricky is a web developer, python hacker, and blogger from DC.
permalink: /:categories/:title
excerpt_separator: <!--more-->
twitter: _rickyreal
url: https://rickydeal.io

# Plugins
plugins:
  - jekyll-sitemap

# Collections
collections:
  portfolio:
    permalink: /:collection/:name
    output: true

# Defaults for different page types
defaults:
  -
    scope:
      path: "assets/**/*.pdf"
    values:
      sitemap: false
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default
  -
    scope:
      path: ""
      type: "portfolio"
    values:
      layout: details
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      image: null
      youtube: null
      spotify: null
      soundcloud: null
      excerpt: false
      spoiler: false
      explicit: false
      categories: []
      tags: []