
title: Conversations With A Ghost
twitter_handle: _rickyreal
description: Ricky is a web developer, python hacker, and blogger from DC.
permalink: /:categories/:title
excerpt_separator: <!--more-->

collections:
  portfolio:
    permalink: /:collection/:name
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default
  -
    scope:
      path: ""
      type: "portfolio"
    values:
      layout: details
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      image_path: null
      youtube: null
      spotify: null
      soundcloud: null
      excerpt: false
      spoiler: false
      explicit: false
      categories: []
      tags: []