
permalink: /:categories/:title
excerpt_separator: <!--more-->

collections:
  portfolio:
    permalink: /:collection/:name

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      image_path: null
      youtube: null
      spotify: null
      soundcloud: null
      excerpt: false
      spoiler: false
      explicit: false
      categories: []
      tags: []