
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

title: Conversations With A Ghost
description: Ricky is a web developer, python hacker, and blogger from DC.
url: https://rickydeal.io
author: Ricky Deal
twitter:
  username: _rickyreal
  card: summary
logo: /images/bitmoji.png
social:
  name: Ricky Deal
  links:
    - https://twitter.com/_rickyreal
    - https://www.facebook.com/Rainerdeal
    - https://www.linkedin.com/in/rickydeal/
    - https://github.com/rainerdeal

permalink: /:categories/:title
excerpt_separator: <!--more-->

collections:
  portfolio:
    permalink: /:collection/:name
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default
  -
    scope:
      path: ""
      type: "portfolio"
    values:
      layout: details
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      image_path: null
      youtube: null
      spotify: null
      soundcloud: null
      excerpt: false
      spoiler: false
      explicit: false
      categories: []
      tags: []