
# Top level defaults
title: Conversations With A Ghost
description: Ricky is a web developer, python hacker, and blogger from DC.
permalink: /:categories/:title
author:
  twitter: _rickyreal
url: https://rickydeal.io

sass:
  style: compressed # possible values: nested, expanded, compact, and compressed

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed

# XML/RSS Feed
feed:
  path: ghost.xml

# Collections
collections:
  portfolio:
    permalink: /:collection/:name
    output: true

# Defaults for different page types
defaults:
  -
    scope:
      path: "assets/**/*.pdf"
    values:
      sitemap: false
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default
  -
    scope:
      path: ""
      type: "portfolio"
    values:
      layout: details
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      image: null
      youtube: null
      spotify: null
      soundcloud: null
      categories: []
      tags: []